# https://circleci.com/docs/2.0/language-javascript/
version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0
jobs:
  node-latest:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn cov:send
      - sonarcloud/scan
      - run: yarn cov:check

workflows:
  build:
    jobs:
      - node-latest:
          context:
            - SonarCloud
